<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.4.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма signup',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'painter@adobe.com',
		'to' => 'painter@adobe.com'
	),
	'recaptcha2' => array(
		'private_key' => '6LeKWuwUAAAAAAq1VkWyxuY1D0QdPG-j_hAjB5V8'
	),
	'fields' => array(
		'custom_U173359' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Ім\'я',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ім\'я\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Електронна пошта',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Електронна пошта\' не может быть пустым.',
				'format' => 'Поле \'Електронна пошта\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U173380' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Прізвище',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Прізвище\' не может быть пустым.'
			)
		),
		'custom_U173393' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Дата народження',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Дата народження\' не может быть пустым.'
			)
		),
		'custom_U173389' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Місто',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Місто\' не может быть пустым.'
			)
		),
		'custom_U173481' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Пароль',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Пароль\' не может быть пустым.'
			)
		),
		'custom_U173498' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Повторіть пароль',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Повторіть пароль\' не может быть пустым.'
			)
		),
		'g-recaptcha-response' => array(
			'order' => 8,
			'type' => 'recaptcha2',
			'label' => 'Проверка',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Проверка\' не может быть пустым.',
				'format' => 'Недействительное значение reCAPTCHA 2.0.'
			)
		)
	)
);

process_form($form);
?>
